import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Literacy Capps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-between mx-10 my-10">
          <Link href="/">Literacy Capps</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
