import './globals.css'

export const metadata = {
  title: 'Literacy Capps',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className='flex justify-between mx-10 my-10'>
          <h1>Literacy Capps</h1>
          <ul>
            <li>
              <a href='#'>Three</a>
            </li>
            <li></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
